[package]
name = "parkforge-build"
version.workspace = true
edition.workspace = true

[dependencies]
fsc_compiler = { git = "https://github.com/Mekurushi/pokepark-fsc.git", rev = "432ed9f448ebf65673f9c992e5df7bfcc4113860" }
fsc_patcher = { git = "https://github.com/Mekurushi/pokepark-fsc.git", rev = "432ed9f448ebf65673f9c992e5df7bfcc4113860" }
tempfile.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[lints]
workspace = true
