[package]
name = "parkforge-build"
version.workspace = true
edition.workspace = true

[dependencies]
fsc_compiler = { git = "https://github.com/Mekurushi/pokepark-fsc.git", rev = "f373ee4d38c487afe231f2507c17a5cadc6bfbb8" }
fsc_diagnostics = { git = "https://github.com/Mekurushi/pokepark-fsc.git", rev = "f373ee4d38c487afe231f2507c17a5cadc6bfbb8" }
fsc_patcher = { git = "https://github.com/Mekurushi/pokepark-fsc.git", rev = "f373ee4d38c487afe231f2507c17a5cadc6bfbb8" }
parkforge-types = { path = "../parkforge-types" }
tempfile.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[lints]
workspace = true
